apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teste-robot-framework
  description: "Aprendizados sobre robot"
  annotations:
    github.com/project-slug: jehtds/teste-robot-framework
spec:
  type: service
  owner: user:jessica
  lifecycle: experimental
